import React, { useEffect } from 'react'
import Button from '@mui/material/Button'
import ButtonGroup from '@mui/material/ButtonGroup'
import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import CardHeader from '@mui/material/CardHeader'
import CardActions from '@mui/material/CardActions'
import Typography from '@mui/material/Typography'
import { Formik, Form, FieldArray, useFormikContext, Field } from 'formik'
import Fields from './fields'
import AddFieldButton from './addfieldbutton'
import EVAFormFieldsPreview from './EVAFormFieldsPreview'
import { useTheme } from '@mui/material/styles'
